os: osx
language: swift
osx_image: xcode9.4

script:
  - xcodebuild test -project Travis-Demo/Travis-Demo.xcodeproj -scheme Travis-Demo -destination "platform=iOS Simulator,name=iPhone 7" -sdk iphonesimulator11.4 CODE_SIGNING_REQUIRED=NO
